// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/commands/v1/validator_commands.proto

package v1

import (
	fmt "fmt"
	math "math"

	vega "code.vegaprotocol.io/sdk-golang/vega"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The kind of the signature created by a node, for example, allow-listing a new asset, withdrawal etc
type NodeSignatureKind int32

const (
	// Represents an unspecified or missing value from the input
	NodeSignatureKind_NODE_SIGNATURE_KIND_UNSPECIFIED NodeSignatureKind = 0
	// Represents a signature for a new asset allow-listing
	NodeSignatureKind_NODE_SIGNATURE_KIND_ASSET_NEW NodeSignatureKind = 1
	// Represents a signature for an asset withdrawal
	NodeSignatureKind_NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL NodeSignatureKind = 2
)

var NodeSignatureKind_name = map[int32]string{
	0: "NODE_SIGNATURE_KIND_UNSPECIFIED",
	1: "NODE_SIGNATURE_KIND_ASSET_NEW",
	2: "NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL",
}

var NodeSignatureKind_value = map[string]int32{
	"NODE_SIGNATURE_KIND_UNSPECIFIED":      0,
	"NODE_SIGNATURE_KIND_ASSET_NEW":        1,
	"NODE_SIGNATURE_KIND_ASSET_WITHDRAWAL": 2,
}

func (x NodeSignatureKind) String() string {
	return proto.EnumName(NodeSignatureKind_name, int32(x))
}

func (NodeSignatureKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_52dee7aaa07d334d, []int{0}
}

// Used to Register a node as a validator during network start-up
type NodeRegistration struct {
	// Vega public key, required field
	VegaPubKey string `protobuf:"bytes,1,opt,name=vega_pub_key,json=vegaPubKey,proto3" json:"vega_pub_key,omitempty"`
	// Ethereum public key, required field
	EthereumAddress string `protobuf:"bytes,2,opt,name=ethereum_address,json=ethereumAddress,proto3" json:"ethereum_address,omitempty"`
	// Public key for the blockchain, required field
	ChainPubKey string `protobuf:"bytes,3,opt,name=chain_pub_key,json=chainPubKey,proto3" json:"chain_pub_key,omitempty"`
	// URL with more info on the node
	InfoUrl string `protobuf:"bytes,4,opt,name=info_url,json=infoUrl,proto3" json:"info_url,omitempty"`
	// Country code (ISO 3166-1 alpha-2) for the location of the node
	Country string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	// ID of the validator, (public master key)
	Id string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the validator
	Name string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	// AvatarURL of the validator
	AvatarUrl string `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// Vega public key derivation index
	VegaPubKeyIndex      uint32   `protobuf:"varint,9,opt,name=vega_pub_key_index,json=vegaPubKeyIndex,proto3" json:"vega_pub_key_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRegistration) Reset()         { *m = NodeRegistration{} }
func (m *NodeRegistration) String() string { return proto.CompactTextString(m) }
func (*NodeRegistration) ProtoMessage()    {}
func (*NodeRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_52dee7aaa07d334d, []int{0}
}

func (m *NodeRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegistration.Unmarshal(m, b)
}
func (m *NodeRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegistration.Marshal(b, m, deterministic)
}
func (m *NodeRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegistration.Merge(m, src)
}
func (m *NodeRegistration) XXX_Size() int {
	return xxx_messageInfo_NodeRegistration.Size(m)
}
func (m *NodeRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegistration proto.InternalMessageInfo

func (m *NodeRegistration) GetVegaPubKey() string {
	if m != nil {
		return m.VegaPubKey
	}
	return ""
}

func (m *NodeRegistration) GetEthereumAddress() string {
	if m != nil {
		return m.EthereumAddress
	}
	return ""
}

func (m *NodeRegistration) GetChainPubKey() string {
	if m != nil {
		return m.ChainPubKey
	}
	return ""
}

func (m *NodeRegistration) GetInfoUrl() string {
	if m != nil {
		return m.InfoUrl
	}
	return ""
}

func (m *NodeRegistration) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *NodeRegistration) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeRegistration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeRegistration) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *NodeRegistration) GetVegaPubKeyIndex() uint32 {
	if m != nil {
		return m.VegaPubKeyIndex
	}
	return 0
}

// Used when a node votes for validating a given resource exists or is valid,
// for example, an ERC20 deposit is valid and exists on ethereum
type NodeVote struct {
	// Public key, required field
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Reference, required field
	Reference            string   `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeVote) Reset()         { *m = NodeVote{} }
func (m *NodeVote) String() string { return proto.CompactTextString(m) }
func (*NodeVote) ProtoMessage()    {}
func (*NodeVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_52dee7aaa07d334d, []int{1}
}

func (m *NodeVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeVote.Unmarshal(m, b)
}
func (m *NodeVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeVote.Marshal(b, m, deterministic)
}
func (m *NodeVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeVote.Merge(m, src)
}
func (m *NodeVote) XXX_Size() int {
	return xxx_messageInfo_NodeVote.Size(m)
}
func (m *NodeVote) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeVote.DiscardUnknown(m)
}

var xxx_messageInfo_NodeVote proto.InternalMessageInfo

func (m *NodeVote) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *NodeVote) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// Represents a signature from a validator, to be used by a foreign chain in order to recognise a decision taken by the Vega network
type NodeSignature struct {
	// The identifier of the resource being signed
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The signature
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	// The kind of resource being signed
	Kind                 NodeSignatureKind `protobuf:"varint,3,opt,name=kind,proto3,enum=vega.commands.v1.NodeSignatureKind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeSignature) Reset()         { *m = NodeSignature{} }
func (m *NodeSignature) String() string { return proto.CompactTextString(m) }
func (*NodeSignature) ProtoMessage()    {}
func (*NodeSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_52dee7aaa07d334d, []int{2}
}

func (m *NodeSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSignature.Unmarshal(m, b)
}
func (m *NodeSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSignature.Marshal(b, m, deterministic)
}
func (m *NodeSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSignature.Merge(m, src)
}
func (m *NodeSignature) XXX_Size() int {
	return xxx_messageInfo_NodeSignature.Size(m)
}
func (m *NodeSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSignature.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSignature proto.InternalMessageInfo

func (m *NodeSignature) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeSignature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *NodeSignature) GetKind() NodeSignatureKind {
	if m != nil {
		return m.Kind
	}
	return NodeSignatureKind_NODE_SIGNATURE_KIND_UNSPECIFIED
}

// An event forwarded to the Vega network to provide information on events happening on other networks
type ChainEvent struct {
	// The identifier of the transaction in which the events happened, usually a hash
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// Arbitrary one-time integer used to prevent replay attacks
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The event
	//
	// Types that are valid to be assigned to Event:
	//	*ChainEvent_Builtin
	//	*ChainEvent_Erc20
	//	*ChainEvent_Btc
	//	*ChainEvent_Validator
	//	*ChainEvent_StakingEvent
	Event                isChainEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChainEvent) Reset()         { *m = ChainEvent{} }
func (m *ChainEvent) String() string { return proto.CompactTextString(m) }
func (*ChainEvent) ProtoMessage()    {}
func (*ChainEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_52dee7aaa07d334d, []int{3}
}

func (m *ChainEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainEvent.Unmarshal(m, b)
}
func (m *ChainEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainEvent.Marshal(b, m, deterministic)
}
func (m *ChainEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainEvent.Merge(m, src)
}
func (m *ChainEvent) XXX_Size() int {
	return xxx_messageInfo_ChainEvent.Size(m)
}
func (m *ChainEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChainEvent proto.InternalMessageInfo

func (m *ChainEvent) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *ChainEvent) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type isChainEvent_Event interface {
	isChainEvent_Event()
}

type ChainEvent_Builtin struct {
	Builtin *vega.BuiltinAssetEvent `protobuf:"bytes,1001,opt,name=builtin,proto3,oneof"`
}

type ChainEvent_Erc20 struct {
	Erc20 *vega.ERC20Event `protobuf:"bytes,1002,opt,name=erc20,proto3,oneof"`
}

type ChainEvent_Btc struct {
	Btc *vega.BTCEvent `protobuf:"bytes,1003,opt,name=btc,proto3,oneof"`
}

type ChainEvent_Validator struct {
	Validator *vega.ValidatorEvent `protobuf:"bytes,1004,opt,name=validator,proto3,oneof"`
}

type ChainEvent_StakingEvent struct {
	StakingEvent *vega.StakingEvent `protobuf:"bytes,1005,opt,name=staking_event,json=stakingEvent,proto3,oneof"`
}

func (*ChainEvent_Builtin) isChainEvent_Event() {}

func (*ChainEvent_Erc20) isChainEvent_Event() {}

func (*ChainEvent_Btc) isChainEvent_Event() {}

func (*ChainEvent_Validator) isChainEvent_Event() {}

func (*ChainEvent_StakingEvent) isChainEvent_Event() {}

func (m *ChainEvent) GetEvent() isChainEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ChainEvent) GetBuiltin() *vega.BuiltinAssetEvent {
	if x, ok := m.GetEvent().(*ChainEvent_Builtin); ok {
		return x.Builtin
	}
	return nil
}

func (m *ChainEvent) GetErc20() *vega.ERC20Event {
	if x, ok := m.GetEvent().(*ChainEvent_Erc20); ok {
		return x.Erc20
	}
	return nil
}

func (m *ChainEvent) GetBtc() *vega.BTCEvent {
	if x, ok := m.GetEvent().(*ChainEvent_Btc); ok {
		return x.Btc
	}
	return nil
}

func (m *ChainEvent) GetValidator() *vega.ValidatorEvent {
	if x, ok := m.GetEvent().(*ChainEvent_Validator); ok {
		return x.Validator
	}
	return nil
}

func (m *ChainEvent) GetStakingEvent() *vega.StakingEvent {
	if x, ok := m.GetEvent().(*ChainEvent_StakingEvent); ok {
		return x.StakingEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ChainEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ChainEvent_Builtin)(nil),
		(*ChainEvent_Erc20)(nil),
		(*ChainEvent_Btc)(nil),
		(*ChainEvent_Validator)(nil),
		(*ChainEvent_StakingEvent)(nil),
	}
}

// A transaction to allow validator to rotate their vega keys
type KeyRotateSubmission struct {
	// New Vega public key derivation index
	NewPubKeyIndex uint32 `protobuf:"varint,1,opt,name=new_pub_key_index,json=newPubKeyIndex,proto3" json:"new_pub_key_index,omitempty"`
	// Target block at which the key rotation will take effect on
	TargetBlock uint64 `protobuf:"varint,2,opt,name=target_block,json=targetBlock,proto3" json:"target_block,omitempty"`
	// The new public key to rotate to
	NewPubKey string `protobuf:"bytes,3,opt,name=new_pub_key,json=newPubKey,proto3" json:"new_pub_key,omitempty"`
	// Hash of currently used public key
	CurrentPubKeyHash    string   `protobuf:"bytes,4,opt,name=current_pub_key_hash,json=currentPubKeyHash,proto3" json:"current_pub_key_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyRotateSubmission) Reset()         { *m = KeyRotateSubmission{} }
func (m *KeyRotateSubmission) String() string { return proto.CompactTextString(m) }
func (*KeyRotateSubmission) ProtoMessage()    {}
func (*KeyRotateSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_52dee7aaa07d334d, []int{4}
}

func (m *KeyRotateSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRotateSubmission.Unmarshal(m, b)
}
func (m *KeyRotateSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRotateSubmission.Marshal(b, m, deterministic)
}
func (m *KeyRotateSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRotateSubmission.Merge(m, src)
}
func (m *KeyRotateSubmission) XXX_Size() int {
	return xxx_messageInfo_KeyRotateSubmission.Size(m)
}
func (m *KeyRotateSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRotateSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRotateSubmission proto.InternalMessageInfo

func (m *KeyRotateSubmission) GetNewPubKeyIndex() uint32 {
	if m != nil {
		return m.NewPubKeyIndex
	}
	return 0
}

func (m *KeyRotateSubmission) GetTargetBlock() uint64 {
	if m != nil {
		return m.TargetBlock
	}
	return 0
}

func (m *KeyRotateSubmission) GetNewPubKey() string {
	if m != nil {
		return m.NewPubKey
	}
	return ""
}

func (m *KeyRotateSubmission) GetCurrentPubKeyHash() string {
	if m != nil {
		return m.CurrentPubKeyHash
	}
	return ""
}

func init() {
	proto.RegisterEnum("vega.commands.v1.NodeSignatureKind", NodeSignatureKind_name, NodeSignatureKind_value)
	proto.RegisterType((*NodeRegistration)(nil), "vega.commands.v1.NodeRegistration")
	proto.RegisterType((*NodeVote)(nil), "vega.commands.v1.NodeVote")
	proto.RegisterType((*NodeSignature)(nil), "vega.commands.v1.NodeSignature")
	proto.RegisterType((*ChainEvent)(nil), "vega.commands.v1.ChainEvent")
	proto.RegisterType((*KeyRotateSubmission)(nil), "vega.commands.v1.KeyRotateSubmission")
}

func init() {
	proto.RegisterFile("vega/commands/v1/validator_commands.proto", fileDescriptor_52dee7aaa07d334d)
}

var fileDescriptor_52dee7aaa07d334d = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xc7, 0xd7, 0x04, 0x42, 0x38, 0x21, 0x59, 0x67, 0x36, 0xd2, 0x5a, 0x2b, 0x6d, 0x93, 0x90,
	0xbd, 0x48, 0xb6, 0x0a, 0x4e, 0xe8, 0x97, 0xd4, 0x3b, 0x3e, 0xdc, 0x06, 0x51, 0xd1, 0xad, 0x21,
	0x9b, 0xaa, 0x37, 0xd6, 0xd8, 0x9e, 0x98, 0x29, 0x30, 0x13, 0x8d, 0xc7, 0x10, 0x1e, 0xa0, 0x6f,
	0xd4, 0x9b, 0xbe, 0x45, 0xdf, 0xa0, 0x52, 0xef, 0xfa, 0xf5, 0x0e, 0xd5, 0x78, 0xb0, 0xf9, 0x68,
	0xf7, 0x0e, 0xff, 0xff, 0xbf, 0xff, 0x39, 0x9e, 0xc3, 0x19, 0xc3, 0xe5, 0x8c, 0x44, 0xd8, 0x0e,
	0xf8, 0x74, 0x8a, 0x59, 0x18, 0xdb, 0xb3, 0x1b, 0x7b, 0x86, 0x27, 0x34, 0xc4, 0x92, 0x0b, 0x2f,
	0x53, 0xeb, 0x8f, 0x82, 0x4b, 0x8e, 0x4c, 0x85, 0xd6, 0x73, 0x71, 0x76, 0xf3, 0xea, 0xa5, 0x0e,
	0x8f, 0x30, 0x65, 0x1e, 0x99, 0x11, 0x26, 0x97, 0xe8, 0xab, 0xcf, 0x23, 0x2a, 0x47, 0x89, 0xaf,
	0x60, 0x7b, 0x3a, 0xa7, 0x72, 0xcc, 0xe7, 0x76, 0xc4, 0xaf, 0x52, 0xf3, 0x2a, 0x6f, 0x10, 0xaf,
	0x7a, 0xe9, 0x5c, 0xed, 0xd7, 0x02, 0x98, 0x7d, 0x1e, 0x12, 0x97, 0x44, 0x34, 0x96, 0x02, 0x4b,
	0xca, 0x19, 0xba, 0x80, 0xaa, 0xea, 0xe3, 0x3d, 0x26, 0xbe, 0x37, 0x26, 0x0b, 0xcb, 0x38, 0x35,
	0x2e, 0x2a, 0xad, 0xdd, 0xdf, 0x7f, 0x3b, 0x29, 0x7c, 0x6f, 0xb8, 0xa0, 0xbc, 0x77, 0x89, 0xdf,
	0x23, 0x0b, 0x74, 0x03, 0x26, 0x91, 0x23, 0x22, 0x48, 0x32, 0xf5, 0x70, 0x18, 0x0a, 0x12, 0xc7,
	0x56, 0x61, 0x83, 0x7e, 0x9e, 0xf9, 0x4d, 0x6d, 0xa3, 0xb7, 0x70, 0xa0, 0xdf, 0x3f, 0xab, 0xbe,
	0xb3, 0xc1, 0xef, 0xa7, 0xe6, 0xb2, 0xfc, 0x19, 0xec, 0x51, 0xf6, 0xc0, 0xbd, 0x44, 0x4c, 0xac,
	0xe2, 0x06, 0x56, 0x56, 0xfa, 0x9d, 0x98, 0xa0, 0x53, 0x28, 0x07, 0x3c, 0x61, 0x52, 0x2c, 0xac,
	0xd2, 0x26, 0xb1, 0x94, 0xd1, 0x21, 0x14, 0x68, 0x68, 0xed, 0x2a, 0xd3, 0x2d, 0xd0, 0x10, 0x21,
	0x28, 0x32, 0x3c, 0x25, 0x56, 0x39, 0x55, 0xd2, 0xdf, 0xe8, 0x35, 0x00, 0x9e, 0x61, 0x89, 0x45,
	0xda, 0x6a, 0x2f, 0x75, 0x2a, 0x5a, 0x51, 0x4d, 0x3e, 0x06, 0xb4, 0x3e, 0x10, 0x8f, 0xb2, 0x90,
	0x3c, 0x59, 0x95, 0x53, 0xe3, 0xe2, 0xc0, 0x7d, 0xbe, 0x1a, 0x47, 0x57, 0xc9, 0xb5, 0xef, 0x60,
	0x4f, 0x4d, 0xf4, 0x3d, 0x97, 0x04, 0x9d, 0x40, 0x79, 0x7d, 0x88, 0xd5, 0xfc, 0xed, 0x76, 0x1f,
	0xf5, 0x09, 0xdf, 0x40, 0x45, 0x90, 0x07, 0x22, 0x08, 0x0b, 0xc8, 0xd6, 0xe4, 0x56, 0x46, 0xed,
	0x47, 0x38, 0x50, 0x25, 0x07, 0x34, 0x62, 0x58, 0x26, 0x82, 0x2c, 0xcf, 0x64, 0xe4, 0x67, 0x32,
	0x61, 0x27, 0xa6, 0x51, 0x5a, 0xa0, 0xea, 0xaa, 0x9f, 0xe8, 0x0b, 0x28, 0x8e, 0x29, 0x0b, 0xd3,
	0xe9, 0x1e, 0x36, 0xce, 0xeb, 0xdb, 0xab, 0x54, 0xdf, 0x28, 0xd8, 0xa3, 0x2c, 0x74, 0xd3, 0x40,
	0xed, 0x97, 0x02, 0x40, 0x5b, 0xfd, 0x07, 0x8e, 0xda, 0x2f, 0xf4, 0x02, 0x4a, 0xf2, 0xc9, 0xcb,
	0x9b, 0x15, 0xe5, 0x53, 0x37, 0x44, 0xc7, 0x50, 0x62, 0x3c, 0x7b, 0xe3, 0xa2, 0xab, 0x1f, 0xd0,
	0xa7, 0x50, 0xf6, 0x13, 0x3a, 0x91, 0x94, 0x59, 0x7f, 0xa8, 0xe1, 0xee, 0x37, 0x5e, 0xea, 0xb6,
	0x2d, 0xad, 0x36, 0xe3, 0x98, 0xc8, 0xb4, 0xea, 0xed, 0x33, 0x37, 0x43, 0xd1, 0x25, 0x94, 0x88,
	0x08, 0x1a, 0xd7, 0xd6, 0x9f, 0x3a, 0x63, 0xea, 0x8c, 0xe3, 0xb6, 0x1b, 0xd7, 0x19, 0xac, 0x09,
	0x74, 0x0e, 0x3b, 0xbe, 0x0c, 0xac, 0xbf, 0x34, 0x78, 0xb8, 0x2c, 0x3e, 0x6c, 0x67, 0x98, 0x72,
	0xd1, 0x67, 0x50, 0xc9, 0x97, 0xdc, 0xfa, 0x5b, 0xa3, 0xc7, 0x1a, 0x7d, 0x9f, 0xe9, 0x59, 0x60,
	0x45, 0xa2, 0x2f, 0xe1, 0x20, 0x96, 0x78, 0x4c, 0x59, 0xa4, 0x2f, 0x96, 0xf5, 0x8f, 0x8e, 0x22,
	0x1d, 0x1d, 0x68, 0x2f, 0x0b, 0x56, 0xe3, 0xb5, 0xe7, 0x56, 0x19, 0x4a, 0x69, 0xa6, 0xf6, 0xb3,
	0x01, 0x2f, 0x7a, 0x64, 0xe1, 0x72, 0x89, 0x25, 0x19, 0x24, 0xfe, 0x94, 0xc6, 0xb1, 0xba, 0x50,
	0x97, 0x70, 0xc4, 0xc8, 0x7c, 0x6b, 0x7d, 0x8c, 0x74, 0x7d, 0x0e, 0x19, 0x99, 0xaf, 0x6d, 0x0f,
	0x3a, 0x83, 0xaa, 0xc4, 0x22, 0x22, 0xd2, 0xf3, 0x27, 0x3c, 0x18, 0x2f, 0x27, 0xbc, 0xaf, 0xb5,
	0x96, 0x92, 0xd0, 0x47, 0xb0, 0xbf, 0x56, 0x4d, 0xdf, 0x1f, 0xb7, 0x92, 0xd7, 0x41, 0x36, 0x1c,
	0x07, 0x89, 0x10, 0x84, 0xc9, 0xbc, 0xe3, 0x08, 0xc7, 0x23, 0x7d, 0x83, 0xdc, 0xa3, 0xa5, 0xa7,
	0xe1, 0x5b, 0x1c, 0x8f, 0xde, 0xfe, 0x64, 0xc0, 0xd1, 0x7f, 0xd6, 0x01, 0x9d, 0xc3, 0x49, 0xff,
	0xdb, 0x8e, 0xe3, 0x0d, 0xba, 0x5f, 0xf7, 0x9b, 0xc3, 0x3b, 0xd7, 0xf1, 0x7a, 0xdd, 0x7e, 0xc7,
	0xbb, 0xeb, 0x0f, 0xde, 0x39, 0xed, 0xee, 0x57, 0x5d, 0xa7, 0x63, 0x3e, 0x43, 0x67, 0xf0, 0xfa,
	0xff, 0xa0, 0xe6, 0x60, 0xe0, 0x0c, 0xbd, 0xbe, 0x73, 0x6f, 0x1a, 0xe8, 0x02, 0xde, 0x7c, 0x18,
	0xb9, 0xef, 0x0e, 0x6f, 0x3b, 0x6e, 0xf3, 0xbe, 0xf9, 0x8d, 0x59, 0x68, 0x35, 0x7e, 0xb8, 0x0e,
	0x78, 0x48, 0xd2, 0x89, 0xa7, 0x9f, 0xa7, 0x80, 0x4f, 0xea, 0x94, 0xdb, 0x71, 0x38, 0xbe, 0x8a,
	0xf8, 0x04, 0xb3, 0xc8, 0xde, 0xfe, 0x78, 0xfa, 0xbb, 0x29, 0xf8, 0xc9, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x6d, 0x7d, 0x95, 0x83, 0x57, 0x05, 0x00, 0x00,
}
