// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/oracles/v1/data.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OracleData describes an oracle data that has been broadcast.
type OracleData struct {
	// pubKeys is the list of authorized public keys that signed the data for this
	// oracle. All the public keys in the oracle data should be contained in these
	// public keys.
	PubKeys []string `protobuf:"bytes,1,rep,name=pub_keys,json=pubKeys,proto3" json:"pub_keys,omitempty"`
	// data holds all the properties of the oracle data
	Data []*Property `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	// matched_specs_ids lists all the oracle specs that matched this oracle data.
	MatchedSpecIds []string `protobuf:"bytes,3,rep,name=matched_spec_ids,json=matchedSpecIds,proto3" json:"matched_spec_ids,omitempty"`
	// broadcast_at is the time at which the data was broadcast for the first
	// time.
	BroadcastAt          int64    `protobuf:"varint,4,opt,name=broadcast_at,json=broadcastAt,proto3" json:"broadcast_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OracleData) Reset()         { *m = OracleData{} }
func (m *OracleData) String() string { return proto.CompactTextString(m) }
func (*OracleData) ProtoMessage()    {}
func (*OracleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_531447dbb4586543, []int{0}
}

func (m *OracleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OracleData.Unmarshal(m, b)
}
func (m *OracleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OracleData.Marshal(b, m, deterministic)
}
func (m *OracleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleData.Merge(m, src)
}
func (m *OracleData) XXX_Size() int {
	return xxx_messageInfo_OracleData.Size(m)
}
func (m *OracleData) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleData.DiscardUnknown(m)
}

var xxx_messageInfo_OracleData proto.InternalMessageInfo

func (m *OracleData) GetPubKeys() []string {
	if m != nil {
		return m.PubKeys
	}
	return nil
}

func (m *OracleData) GetData() []*Property {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OracleData) GetMatchedSpecIds() []string {
	if m != nil {
		return m.MatchedSpecIds
	}
	return nil
}

func (m *OracleData) GetBroadcastAt() int64 {
	if m != nil {
		return m.BroadcastAt
	}
	return 0
}

// Property describes one property of an oracle spec with a key with its value.
type Property struct {
	// name is the name of the property.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value is the value of the property.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_531447dbb4586543, []int{1}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*OracleData)(nil), "oracles.v1.OracleData")
	proto.RegisterType((*Property)(nil), "oracles.v1.Property")
}

func init() { proto.RegisterFile("vega/oracles/v1/data.proto", fileDescriptor_531447dbb4586543) }

var fileDescriptor_531447dbb4586543 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x6e, 0xd5, 0x76, 0x2a, 0x22, 0xa1, 0x87, 0xe8, 0x69, 0xed, 0x29, 0x17, 0x13,
	0x56, 0x7d, 0x01, 0xc5, 0x8b, 0x78, 0x50, 0xd6, 0x9b, 0x97, 0x65, 0x36, 0x19, 0xd6, 0xd2, 0x6d,
	0x13, 0x92, 0xec, 0xc2, 0xbe, 0x8c, 0xcf, 0x2a, 0x8d, 0x55, 0xc1, 0xdb, 0xfc, 0x1f, 0x3f, 0x1f,
	0xcc, 0x0f, 0x97, 0x03, 0xb5, 0xa8, 0xac, 0x47, 0xdd, 0x51, 0x50, 0x43, 0xa9, 0x0c, 0x46, 0x94,
	0xce, 0xdb, 0x68, 0x19, 0x1c, 0xb0, 0x1c, 0xca, 0xd5, 0x67, 0x06, 0xf0, 0x92, 0xe2, 0x23, 0x46,
	0x64, 0x17, 0x30, 0x73, 0x7d, 0x53, 0x6f, 0x68, 0x0c, 0x3c, 0x2b, 0x72, 0x31, 0xaf, 0x4e, 0x5c,
	0xdf, 0x3c, 0xd3, 0x18, 0x98, 0x80, 0xe9, 0xde, 0xc1, 0x27, 0x45, 0x2e, 0x16, 0x37, 0x4b, 0xf9,
	0x27, 0x91, 0xaf, 0xde, 0x3a, 0xf2, 0x71, 0xac, 0x52, 0x83, 0x09, 0x38, 0xdf, 0x62, 0xd4, 0x1f,
	0x64, 0xea, 0xe0, 0x48, 0xd7, 0x6b, 0x13, 0x78, 0x9e, 0x64, 0x67, 0x07, 0xfe, 0xe6, 0x48, 0x3f,
	0x99, 0xc0, 0xae, 0xe0, 0xb4, 0xf1, 0x16, 0x8d, 0xc6, 0x10, 0x6b, 0x8c, 0x7c, 0x5a, 0x64, 0x22,
	0xaf, 0x16, 0xbf, 0xec, 0x3e, 0xae, 0xee, 0x60, 0xf6, 0xa3, 0x67, 0x0c, 0xa6, 0x3b, 0xdc, 0x12,
	0xcf, 0x8a, 0x4c, 0xcc, 0xab, 0x74, 0xb3, 0x25, 0x1c, 0x0d, 0xd8, 0xf5, 0xc4, 0x27, 0x09, 0x7e,
	0x87, 0x87, 0xf2, 0x5d, 0x69, 0x6b, 0x48, 0xee, 0x57, 0x48, 0x4f, 0x6b, 0xdb, 0xc9, 0xb5, 0x55,
	0xc1, 0x6c, 0xae, 0x5b, 0xdb, 0xe1, 0xae, 0x55, 0xff, 0x06, 0x6a, 0x8e, 0x53, 0xef, 0xf6, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0x24, 0x01, 0xec, 0xcd, 0x3a, 0x01, 0x00, 0x00,
}
