// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/api/v1/core.proto

package v1

import (
	fmt "fmt"
	math "math"

	vega "code.vegaprotocol.io/sdk-golang/vega"
	v1 "code.vegaprotocol.io/sdk-golang/vega/commands/v1"
	v11 "code.vegaprotocol.io/sdk-golang/vega/events/v1"
	_ "code.vegaprotocol.io/sdk-golang/vega/oracles/v1"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Blockchain transaction type
type SubmitTransactionRequest_Type int32

const (
	SubmitTransactionRequest_TYPE_UNSPECIFIED SubmitTransactionRequest_Type = 0
	// The transaction will be submitted without waiting for response
	SubmitTransactionRequest_TYPE_ASYNC SubmitTransactionRequest_Type = 1
	// The transaction will be submitted, and blocking until the
	// tendermint mempool return a response
	SubmitTransactionRequest_TYPE_SYNC SubmitTransactionRequest_Type = 2
	// The transaction will submitted, and blocking until the tendermint
	// network will have committed it into a block
	SubmitTransactionRequest_TYPE_COMMIT SubmitTransactionRequest_Type = 3
)

var SubmitTransactionRequest_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "TYPE_ASYNC",
	2: "TYPE_SYNC",
	3: "TYPE_COMMIT",
}

var SubmitTransactionRequest_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"TYPE_ASYNC":       1,
	"TYPE_SYNC":        2,
	"TYPE_COMMIT":      3,
}

func (x SubmitTransactionRequest_Type) String() string {
	return proto.EnumName(SubmitTransactionRequest_Type_name, int32(x))
}

func (SubmitTransactionRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{2, 0}
}

// Request for a new event sent by the blockchain queue to be propagated on Vega
type PropagateChainEventRequest struct {
	// Chain event
	Event []byte `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Public key
	PubKey string `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Signature
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropagateChainEventRequest) Reset()         { *m = PropagateChainEventRequest{} }
func (m *PropagateChainEventRequest) String() string { return proto.CompactTextString(m) }
func (*PropagateChainEventRequest) ProtoMessage()    {}
func (*PropagateChainEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{0}
}

func (m *PropagateChainEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateChainEventRequest.Unmarshal(m, b)
}
func (m *PropagateChainEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateChainEventRequest.Marshal(b, m, deterministic)
}
func (m *PropagateChainEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateChainEventRequest.Merge(m, src)
}
func (m *PropagateChainEventRequest) XXX_Size() int {
	return xxx_messageInfo_PropagateChainEventRequest.Size(m)
}
func (m *PropagateChainEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateChainEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateChainEventRequest proto.InternalMessageInfo

func (m *PropagateChainEventRequest) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *PropagateChainEventRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *PropagateChainEventRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Response for a new event sent by the blockchain queue to be propagated on Vega
type PropagateChainEventResponse struct {
	// Success will be true if the event was accepted by the node,
	// **Important** - success does not mean that the event is confirmed by consensus
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropagateChainEventResponse) Reset()         { *m = PropagateChainEventResponse{} }
func (m *PropagateChainEventResponse) String() string { return proto.CompactTextString(m) }
func (*PropagateChainEventResponse) ProtoMessage()    {}
func (*PropagateChainEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{1}
}

func (m *PropagateChainEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateChainEventResponse.Unmarshal(m, b)
}
func (m *PropagateChainEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateChainEventResponse.Marshal(b, m, deterministic)
}
func (m *PropagateChainEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateChainEventResponse.Merge(m, src)
}
func (m *PropagateChainEventResponse) XXX_Size() int {
	return xxx_messageInfo_PropagateChainEventResponse.Size(m)
}
func (m *PropagateChainEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateChainEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateChainEventResponse proto.InternalMessageInfo

func (m *PropagateChainEventResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Request for submitting a transaction v2 on Vega
type SubmitTransactionRequest struct {
	// A bundle of signed payload and signature, to form a transaction that will be submitted to the Vega blockchain
	Tx *v1.Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// Type of transaction request, for example ASYNC, meaning the transaction will be submitted and not block on a response
	Type                 SubmitTransactionRequest_Type `protobuf:"varint,2,opt,name=type,proto3,enum=vega.api.v1.SubmitTransactionRequest_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SubmitTransactionRequest) Reset()         { *m = SubmitTransactionRequest{} }
func (m *SubmitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionRequest) ProtoMessage()    {}
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{2}
}

func (m *SubmitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionRequest.Merge(m, src)
}
func (m *SubmitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionRequest.Size(m)
}
func (m *SubmitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionRequest proto.InternalMessageInfo

func (m *SubmitTransactionRequest) GetTx() *v1.Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SubmitTransactionRequest) GetType() SubmitTransactionRequest_Type {
	if m != nil {
		return m.Type
	}
	return SubmitTransactionRequest_TYPE_UNSPECIFIED
}

// Response for submitting a transaction v2 on Vega
type SubmitTransactionResponse struct {
	// Success will be true if the transaction was accepted by the node,
	// **Important** - success does not mean that the event is confirmed by consensus
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Hash of the transaction, if accepted
	TxHash               string   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitTransactionResponse) Reset()         { *m = SubmitTransactionResponse{} }
func (m *SubmitTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionResponse) ProtoMessage()    {}
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{3}
}

func (m *SubmitTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionResponse.Unmarshal(m, b)
}
func (m *SubmitTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionResponse.Merge(m, src)
}
func (m *SubmitTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionResponse.Size(m)
}
func (m *SubmitTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionResponse proto.InternalMessageInfo

func (m *SubmitTransactionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SubmitTransactionResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// Request for the current time of the vega network
type GetVegaTimeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVegaTimeRequest) Reset()         { *m = GetVegaTimeRequest{} }
func (m *GetVegaTimeRequest) String() string { return proto.CompactTextString(m) }
func (*GetVegaTimeRequest) ProtoMessage()    {}
func (*GetVegaTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{4}
}

func (m *GetVegaTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVegaTimeRequest.Unmarshal(m, b)
}
func (m *GetVegaTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVegaTimeRequest.Marshal(b, m, deterministic)
}
func (m *GetVegaTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVegaTimeRequest.Merge(m, src)
}
func (m *GetVegaTimeRequest) XXX_Size() int {
	return xxx_messageInfo_GetVegaTimeRequest.Size(m)
}
func (m *GetVegaTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVegaTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVegaTimeRequest proto.InternalMessageInfo

// Response for the current consensus coordinated time on the Vega network, referred to as "VegaTime"
type GetVegaTimeResponse struct {
	// Timestamp representation of current VegaTime as represented in
	// Nanoseconds since the epoch, for example `1580473859111222333` corresponds to `2020-01-31T12:30:59.111222333Z`
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVegaTimeResponse) Reset()         { *m = GetVegaTimeResponse{} }
func (m *GetVegaTimeResponse) String() string { return proto.CompactTextString(m) }
func (*GetVegaTimeResponse) ProtoMessage()    {}
func (*GetVegaTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{5}
}

func (m *GetVegaTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVegaTimeResponse.Unmarshal(m, b)
}
func (m *GetVegaTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVegaTimeResponse.Marshal(b, m, deterministic)
}
func (m *GetVegaTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVegaTimeResponse.Merge(m, src)
}
func (m *GetVegaTimeResponse) XXX_Size() int {
	return xxx_messageInfo_GetVegaTimeResponse.Size(m)
}
func (m *GetVegaTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVegaTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVegaTimeResponse proto.InternalMessageInfo

func (m *GetVegaTimeResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Request to subscribe to a stream of one or more event types from the Vega event bus
type ObserveEventBusRequest struct {
	// One or more types of event, required field
	Type []v11.BusEventType `protobuf:"varint,1,rep,packed,name=type,proto3,enum=vega.events.v1.BusEventType" json:"type,omitempty"`
	// Market identifier, optional field
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Party identifier, optional field
	PartyId string `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Batch size, optional field -
	// If not specified, any events received will be sent immediately. If the client is not ready
	// for the next data-set, data may be dropped a number of times, and eventually the stream is closed.
	// if specified, the first batch will be sent when ready. To receive the next set of events, the client
	// must write an `ObserveEventBatch` message on the stream to flush the buffer.
	// If no message is received in 5 seconds, the stream is closed.
	// Default: 0, send any and all events when they are available.
	BatchSize            int64    `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObserveEventBusRequest) Reset()         { *m = ObserveEventBusRequest{} }
func (m *ObserveEventBusRequest) String() string { return proto.CompactTextString(m) }
func (*ObserveEventBusRequest) ProtoMessage()    {}
func (*ObserveEventBusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{6}
}

func (m *ObserveEventBusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObserveEventBusRequest.Unmarshal(m, b)
}
func (m *ObserveEventBusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObserveEventBusRequest.Marshal(b, m, deterministic)
}
func (m *ObserveEventBusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveEventBusRequest.Merge(m, src)
}
func (m *ObserveEventBusRequest) XXX_Size() int {
	return xxx_messageInfo_ObserveEventBusRequest.Size(m)
}
func (m *ObserveEventBusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveEventBusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveEventBusRequest proto.InternalMessageInfo

func (m *ObserveEventBusRequest) GetType() []v11.BusEventType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ObserveEventBusRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *ObserveEventBusRequest) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *ObserveEventBusRequest) GetBatchSize() int64 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

// Response to a subscribed stream of events from the Vega event bus
type ObserveEventBusResponse struct {
	// One or more events
	Events               []*v11.BusEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObserveEventBusResponse) Reset()         { *m = ObserveEventBusResponse{} }
func (m *ObserveEventBusResponse) String() string { return proto.CompactTextString(m) }
func (*ObserveEventBusResponse) ProtoMessage()    {}
func (*ObserveEventBusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{7}
}

func (m *ObserveEventBusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObserveEventBusResponse.Unmarshal(m, b)
}
func (m *ObserveEventBusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObserveEventBusResponse.Marshal(b, m, deterministic)
}
func (m *ObserveEventBusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveEventBusResponse.Merge(m, src)
}
func (m *ObserveEventBusResponse) XXX_Size() int {
	return xxx_messageInfo_ObserveEventBusResponse.Size(m)
}
func (m *ObserveEventBusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveEventBusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveEventBusResponse proto.InternalMessageInfo

func (m *ObserveEventBusResponse) GetEvents() []*v11.BusEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

// A a request for statistics about the Vega network
type StatisticsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticsRequest) Reset()         { *m = StatisticsRequest{} }
func (m *StatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*StatisticsRequest) ProtoMessage()    {}
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{8}
}

func (m *StatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsRequest.Unmarshal(m, b)
}
func (m *StatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsRequest.Marshal(b, m, deterministic)
}
func (m *StatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsRequest.Merge(m, src)
}
func (m *StatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_StatisticsRequest.Size(m)
}
func (m *StatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsRequest proto.InternalMessageInfo

type StatisticsResponse struct {
	Statistics           *Statistics `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatisticsResponse) Reset()         { *m = StatisticsResponse{} }
func (m *StatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*StatisticsResponse) ProtoMessage()    {}
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{9}
}

func (m *StatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsResponse.Unmarshal(m, b)
}
func (m *StatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsResponse.Marshal(b, m, deterministic)
}
func (m *StatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsResponse.Merge(m, src)
}
func (m *StatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_StatisticsResponse.Size(m)
}
func (m *StatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsResponse proto.InternalMessageInfo

func (m *StatisticsResponse) GetStatistics() *Statistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

// Vega domain specific statistics as reported by the node the caller is connected to
type Statistics struct {
	// Current block height as reported by the Vega blockchain
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Current backlog length (number of transactions) that are waiting to be included in a block
	BacklogLength uint64 `protobuf:"varint,2,opt,name=backlog_length,json=backlogLength,proto3" json:"backlog_length,omitempty"`
	// Total number of connected peers to this node
	TotalPeers uint64 `protobuf:"varint,3,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`
	// Genesis block date and time formatted in ISO-8601 datetime format with nanosecond precision
	GenesisTime string `protobuf:"bytes,4,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	// Current system date and time formatted in ISO-8601 datetime format with nanosecond precision
	CurrentTime string `protobuf:"bytes,5,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	// Current Vega date and time formatted in ISO-8601 datetime format with nanosecond precision
	VegaTime string `protobuf:"bytes,6,opt,name=vega_time,json=vegaTime,proto3" json:"vega_time,omitempty"`
	// Status of the connection to the Vega blockchain
	// - See [`ChainStatus`](#vega.ChainStatus)
	Status vega.ChainStatus `protobuf:"varint,7,opt,name=status,proto3,enum=vega.ChainStatus" json:"status,omitempty"`
	// Transactions per block
	TxPerBlock uint64 `protobuf:"varint,8,opt,name=tx_per_block,json=txPerBlock,proto3" json:"tx_per_block,omitempty"`
	// Average transaction size in bytes
	AverageTxBytes uint64 `protobuf:"varint,9,opt,name=average_tx_bytes,json=averageTxBytes,proto3" json:"average_tx_bytes,omitempty"`
	// Average orders per block
	AverageOrdersPerBlock uint64 `protobuf:"varint,10,opt,name=average_orders_per_block,json=averageOrdersPerBlock,proto3" json:"average_orders_per_block,omitempty"`
	// Trades emitted per second
	TradesPerSecond uint64 `protobuf:"varint,11,opt,name=trades_per_second,json=tradesPerSecond,proto3" json:"trades_per_second,omitempty"`
	// Orders processed per second
	OrdersPerSecond uint64 `protobuf:"varint,12,opt,name=orders_per_second,json=ordersPerSecond,proto3" json:"orders_per_second,omitempty"`
	// Total markets on this Vega network
	TotalMarkets uint64 `protobuf:"varint,13,opt,name=total_markets,json=totalMarkets,proto3" json:"total_markets,omitempty"`
	// Total number of order amendments since genesis (on all markets)
	TotalAmendOrder uint64 `protobuf:"varint,16,opt,name=total_amend_order,json=totalAmendOrder,proto3" json:"total_amend_order,omitempty"`
	// Total number of order cancellations since genesis (on all markets)
	TotalCancelOrder uint64 `protobuf:"varint,17,opt,name=total_cancel_order,json=totalCancelOrder,proto3" json:"total_cancel_order,omitempty"`
	// Total number of order submissions since genesis (on all markets)
	TotalCreateOrder uint64 `protobuf:"varint,18,opt,name=total_create_order,json=totalCreateOrder,proto3" json:"total_create_order,omitempty"`
	// Total number of orders processed since genesis (on all markets)
	TotalOrders uint64 `protobuf:"varint,19,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	// Total number of trades emitted since genesis (on all markets)
	TotalTrades uint64 `protobuf:"varint,20,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	// Current number of stream subscribers to order data
	OrderSubscriptions uint32 `protobuf:"varint,21,opt,name=order_subscriptions,json=orderSubscriptions,proto3" json:"order_subscriptions,omitempty"`
	// Current number of stream subscribers to trade data
	TradeSubscriptions uint32 `protobuf:"varint,22,opt,name=trade_subscriptions,json=tradeSubscriptions,proto3" json:"trade_subscriptions,omitempty"`
	// Current number of stream subscribers to candle-stick data
	CandleSubscriptions uint32 `protobuf:"varint,23,opt,name=candle_subscriptions,json=candleSubscriptions,proto3" json:"candle_subscriptions,omitempty"`
	// Current number of stream subscribers to market depth data
	MarketDepthSubscriptions uint32 `protobuf:"varint,24,opt,name=market_depth_subscriptions,json=marketDepthSubscriptions,proto3" json:"market_depth_subscriptions,omitempty"`
	// Current number of stream subscribers to positions data
	PositionsSubscriptions uint32 `protobuf:"varint,25,opt,name=positions_subscriptions,json=positionsSubscriptions,proto3" json:"positions_subscriptions,omitempty"`
	// Current number of stream subscribers to account data
	AccountSubscriptions uint32 `protobuf:"varint,26,opt,name=account_subscriptions,json=accountSubscriptions,proto3" json:"account_subscriptions,omitempty"`
	// Current number of stream subscribers to market data
	MarketDataSubscriptions uint32 `protobuf:"varint,27,opt,name=market_data_subscriptions,json=marketDataSubscriptions,proto3" json:"market_data_subscriptions,omitempty"`
	// The version hash of the Vega node software
	AppVersionHash string `protobuf:"bytes,28,opt,name=app_version_hash,json=appVersionHash,proto3" json:"app_version_hash,omitempty"`
	// The version of the Vega node software
	AppVersion string `protobuf:"bytes,29,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// The version of the underlying Vega blockchain
	ChainVersion string `protobuf:"bytes,30,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	// Current block duration, in nanoseconds
	BlockDuration uint64 `protobuf:"varint,31,opt,name=block_duration,json=blockDuration,proto3" json:"block_duration,omitempty"`
	// Total uptime for this node formatted in ISO-8601 datetime format with nanosecond precision
	Uptime string `protobuf:"bytes,32,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Unique identifier for the underlying Vega blockchain
	ChainId string `protobuf:"bytes,33,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Current number of stream subscribers to market depth update data
	MarketDepthUpdatesSubscriptions uint32   `protobuf:"varint,34,opt,name=market_depth_updates_subscriptions,json=marketDepthUpdatesSubscriptions,proto3" json:"market_depth_updates_subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{10}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Statistics) GetBacklogLength() uint64 {
	if m != nil {
		return m.BacklogLength
	}
	return 0
}

func (m *Statistics) GetTotalPeers() uint64 {
	if m != nil {
		return m.TotalPeers
	}
	return 0
}

func (m *Statistics) GetGenesisTime() string {
	if m != nil {
		return m.GenesisTime
	}
	return ""
}

func (m *Statistics) GetCurrentTime() string {
	if m != nil {
		return m.CurrentTime
	}
	return ""
}

func (m *Statistics) GetVegaTime() string {
	if m != nil {
		return m.VegaTime
	}
	return ""
}

func (m *Statistics) GetStatus() vega.ChainStatus {
	if m != nil {
		return m.Status
	}
	return vega.ChainStatus_CHAIN_STATUS_UNSPECIFIED
}

func (m *Statistics) GetTxPerBlock() uint64 {
	if m != nil {
		return m.TxPerBlock
	}
	return 0
}

func (m *Statistics) GetAverageTxBytes() uint64 {
	if m != nil {
		return m.AverageTxBytes
	}
	return 0
}

func (m *Statistics) GetAverageOrdersPerBlock() uint64 {
	if m != nil {
		return m.AverageOrdersPerBlock
	}
	return 0
}

func (m *Statistics) GetTradesPerSecond() uint64 {
	if m != nil {
		return m.TradesPerSecond
	}
	return 0
}

func (m *Statistics) GetOrdersPerSecond() uint64 {
	if m != nil {
		return m.OrdersPerSecond
	}
	return 0
}

func (m *Statistics) GetTotalMarkets() uint64 {
	if m != nil {
		return m.TotalMarkets
	}
	return 0
}

func (m *Statistics) GetTotalAmendOrder() uint64 {
	if m != nil {
		return m.TotalAmendOrder
	}
	return 0
}

func (m *Statistics) GetTotalCancelOrder() uint64 {
	if m != nil {
		return m.TotalCancelOrder
	}
	return 0
}

func (m *Statistics) GetTotalCreateOrder() uint64 {
	if m != nil {
		return m.TotalCreateOrder
	}
	return 0
}

func (m *Statistics) GetTotalOrders() uint64 {
	if m != nil {
		return m.TotalOrders
	}
	return 0
}

func (m *Statistics) GetTotalTrades() uint64 {
	if m != nil {
		return m.TotalTrades
	}
	return 0
}

func (m *Statistics) GetOrderSubscriptions() uint32 {
	if m != nil {
		return m.OrderSubscriptions
	}
	return 0
}

func (m *Statistics) GetTradeSubscriptions() uint32 {
	if m != nil {
		return m.TradeSubscriptions
	}
	return 0
}

func (m *Statistics) GetCandleSubscriptions() uint32 {
	if m != nil {
		return m.CandleSubscriptions
	}
	return 0
}

func (m *Statistics) GetMarketDepthSubscriptions() uint32 {
	if m != nil {
		return m.MarketDepthSubscriptions
	}
	return 0
}

func (m *Statistics) GetPositionsSubscriptions() uint32 {
	if m != nil {
		return m.PositionsSubscriptions
	}
	return 0
}

func (m *Statistics) GetAccountSubscriptions() uint32 {
	if m != nil {
		return m.AccountSubscriptions
	}
	return 0
}

func (m *Statistics) GetMarketDataSubscriptions() uint32 {
	if m != nil {
		return m.MarketDataSubscriptions
	}
	return 0
}

func (m *Statistics) GetAppVersionHash() string {
	if m != nil {
		return m.AppVersionHash
	}
	return ""
}

func (m *Statistics) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *Statistics) GetChainVersion() string {
	if m != nil {
		return m.ChainVersion
	}
	return ""
}

func (m *Statistics) GetBlockDuration() uint64 {
	if m != nil {
		return m.BlockDuration
	}
	return 0
}

func (m *Statistics) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *Statistics) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Statistics) GetMarketDepthUpdatesSubscriptions() uint32 {
	if m != nil {
		return m.MarketDepthUpdatesSubscriptions
	}
	return 0
}

// A request to get the height of the very last block processed
// by tendermint
type LastBlockHeightRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBlockHeightRequest) Reset()         { *m = LastBlockHeightRequest{} }
func (m *LastBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*LastBlockHeightRequest) ProtoMessage()    {}
func (*LastBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{11}
}

func (m *LastBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlockHeightRequest.Unmarshal(m, b)
}
func (m *LastBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *LastBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlockHeightRequest.Merge(m, src)
}
func (m *LastBlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_LastBlockHeightRequest.Size(m)
}
func (m *LastBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlockHeightRequest proto.InternalMessageInfo

// A response with the height of the last block processed by
// tendermint
type LastBlockHeightResponse struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBlockHeightResponse) Reset()         { *m = LastBlockHeightResponse{} }
func (m *LastBlockHeightResponse) String() string { return proto.CompactTextString(m) }
func (*LastBlockHeightResponse) ProtoMessage()    {}
func (*LastBlockHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b743bbbcd011275, []int{12}
}

func (m *LastBlockHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlockHeightResponse.Unmarshal(m, b)
}
func (m *LastBlockHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlockHeightResponse.Marshal(b, m, deterministic)
}
func (m *LastBlockHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlockHeightResponse.Merge(m, src)
}
func (m *LastBlockHeightResponse) XXX_Size() int {
	return xxx_messageInfo_LastBlockHeightResponse.Size(m)
}
func (m *LastBlockHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlockHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlockHeightResponse proto.InternalMessageInfo

func (m *LastBlockHeightResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("vega.api.v1.SubmitTransactionRequest_Type", SubmitTransactionRequest_Type_name, SubmitTransactionRequest_Type_value)
	proto.RegisterType((*PropagateChainEventRequest)(nil), "vega.api.v1.PropagateChainEventRequest")
	proto.RegisterType((*PropagateChainEventResponse)(nil), "vega.api.v1.PropagateChainEventResponse")
	proto.RegisterType((*SubmitTransactionRequest)(nil), "vega.api.v1.SubmitTransactionRequest")
	proto.RegisterType((*SubmitTransactionResponse)(nil), "vega.api.v1.SubmitTransactionResponse")
	proto.RegisterType((*GetVegaTimeRequest)(nil), "vega.api.v1.GetVegaTimeRequest")
	proto.RegisterType((*GetVegaTimeResponse)(nil), "vega.api.v1.GetVegaTimeResponse")
	proto.RegisterType((*ObserveEventBusRequest)(nil), "vega.api.v1.ObserveEventBusRequest")
	proto.RegisterType((*ObserveEventBusResponse)(nil), "vega.api.v1.ObserveEventBusResponse")
	proto.RegisterType((*StatisticsRequest)(nil), "vega.api.v1.StatisticsRequest")
	proto.RegisterType((*StatisticsResponse)(nil), "vega.api.v1.StatisticsResponse")
	proto.RegisterType((*Statistics)(nil), "vega.api.v1.Statistics")
	proto.RegisterType((*LastBlockHeightRequest)(nil), "vega.api.v1.LastBlockHeightRequest")
	proto.RegisterType((*LastBlockHeightResponse)(nil), "vega.api.v1.LastBlockHeightResponse")
}

func init() { proto.RegisterFile("vega/api/v1/core.proto", fileDescriptor_1b743bbbcd011275) }

var fileDescriptor_1b743bbbcd011275 = []byte{
	// 1366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xff, 0x6e, 0xdb, 0xb6,
	0x13, 0xff, 0x3a, 0x49, 0x93, 0xf8, 0x9c, 0x9f, 0x4c, 0x62, 0x2b, 0x4e, 0xda, 0xb8, 0xea, 0xb7,
	0x9b, 0xdb, 0x2d, 0x76, 0x93, 0x02, 0x0b, 0x30, 0x0c, 0x03, 0x9a, 0x34, 0x5b, 0x83, 0x36, 0xad,
	0x61, 0xbb, 0x05, 0x3a, 0x0c, 0xd0, 0x68, 0x89, 0x90, 0x85, 0xd8, 0xa2, 0x46, 0x52, 0xae, 0xd3,
	0xb7, 0xd9, 0x7b, 0xec, 0x3d, 0xf6, 0x0c, 0x7b, 0x8b, 0x81, 0x47, 0x3a, 0xb6, 0x9c, 0x78, 0xdd,
	0x7f, 0xe6, 0xe7, 0x07, 0xef, 0x74, 0x24, 0x8f, 0x34, 0x14, 0x07, 0x2c, 0xa4, 0x75, 0x9a, 0x44,
	0xf5, 0xc1, 0x51, 0xdd, 0xe7, 0x82, 0xd5, 0x12, 0xc1, 0x15, 0x27, 0x05, 0x8d, 0xd7, 0x68, 0x12,
	0xd5, 0x06, 0x47, 0xe5, 0x75, 0x14, 0x21, 0x82, 0x6c, 0x99, 0x20, 0xd0, 0xa7, 0xe2, 0x8a, 0x29,
	0x69, 0xb1, 0x1d, 0xc4, 0x42, 0x3e, 0x60, 0x22, 0xa6, 0xb1, 0x6f, 0x27, 0x2a, 0x6f, 0x9a, 0x00,
	0x52, 0x8e, 0x95, 0x7b, 0x08, 0xb1, 0x01, 0x8b, 0x95, 0xd4, 0x61, 0xcd, 0x2f, 0x4b, 0x96, 0x91,
	0xe4, 0x82, 0xfa, 0x3d, 0x86, 0xac, 0x4c, 0x98, 0x3f, 0x8b, 0x0b, 0xa8, 0x1a, 0xa5, 0x74, 0x80,
	0x9c, 0xcf, 0xfb, 0x7d, 0x1a, 0x07, 0xd2, 0x7c, 0x8d, 0xf9, 0x6d, 0x05, 0xee, 0x2d, 0x81, 0x12,
	0x34, 0x96, 0xd4, 0x57, 0x11, 0x8f, 0xad, 0xe6, 0xc9, 0x2d, 0xcd, 0x80, 0xf6, 0xa2, 0x80, 0x2a,
	0x2e, 0xbc, 0xa9, 0xe9, 0xbe, 0x0b, 0x23, 0xd5, 0x4d, 0x3b, 0x35, 0x9f, 0xf7, 0xeb, 0xfd, 0x4f,
	0x91, 0xba, 0xe2, 0x9f, 0xea, 0x21, 0x3f, 0x44, 0xf2, 0xf0, 0xc6, 0x25, 0xc7, 0x13, 0x18, 0x9f,
	0x1b, 0x41, 0xb9, 0x21, 0x78, 0x42, 0x43, 0xaa, 0xd8, 0x59, 0x97, 0x46, 0xf1, 0xb9, 0xfe, 0xfa,
	0x26, 0xfb, 0x3d, 0x65, 0x52, 0x91, 0x6d, 0xb8, 0x87, 0xd5, 0x70, 0x72, 0x95, 0x5c, 0x75, 0xa5,
	0x69, 0x06, 0xa4, 0x04, 0x4b, 0x49, 0xda, 0xf1, 0xae, 0xd8, 0xb5, 0x33, 0x57, 0xc9, 0x55, 0xf3,
	0xcd, 0xc5, 0x24, 0xed, 0xbc, 0x66, 0xd7, 0x64, 0x1f, 0xf2, 0x32, 0x0a, 0x63, 0xaa, 0x52, 0xc1,
	0x9c, 0x79, 0xb4, 0x8c, 0x01, 0xf7, 0x04, 0xf6, 0xee, 0x0c, 0x25, 0x13, 0x1e, 0x4b, 0x46, 0x1c,
	0x58, 0x92, 0xa9, 0xef, 0x33, 0x29, 0x31, 0xda, 0x72, 0x73, 0x34, 0x74, 0xff, 0xca, 0x81, 0xd3,
	0x4a, 0x3b, 0xfd, 0x48, 0xb5, 0xc7, 0x25, 0x1a, 0xa5, 0x78, 0x08, 0x73, 0x6a, 0x88, 0x8e, 0xc2,
	0xf1, 0xfd, 0x1a, 0x6e, 0x8a, 0x9b, 0xd2, 0x0c, 0x8e, 0x6a, 0x93, 0x8e, 0x39, 0x35, 0x24, 0x3f,
	0xc2, 0x82, 0xba, 0x4e, 0x18, 0x26, 0xbe, 0x76, 0xfc, 0xb4, 0x36, 0xb1, 0xaf, 0x6a, 0xb3, 0x62,
	0xd4, 0xda, 0xd7, 0x09, 0x6b, 0xa2, 0xcf, 0x7d, 0x03, 0x0b, 0x7a, 0x44, 0xb6, 0x61, 0xa3, 0xfd,
	0xb1, 0x71, 0xee, 0xbd, 0x7f, 0xdb, 0x6a, 0x9c, 0x9f, 0x5d, 0xfc, 0x74, 0x71, 0xfe, 0x72, 0xe3,
	0x7f, 0x64, 0x0d, 0x00, 0xd1, 0x17, 0xad, 0x8f, 0x6f, 0xcf, 0x36, 0x72, 0x64, 0x15, 0xf2, 0x38,
	0xc6, 0xe1, 0x1c, 0x59, 0x87, 0x02, 0x0e, 0xcf, 0xde, 0x5d, 0x5e, 0x5e, 0xb4, 0x37, 0xe6, 0xdd,
	0xb7, 0xb0, 0x7b, 0x47, 0xd0, 0x2f, 0x15, 0x44, 0x2f, 0x80, 0x1a, 0x7a, 0x5d, 0x2a, 0xbb, 0xa3,
	0x05, 0x50, 0xc3, 0x57, 0x54, 0x76, 0xdd, 0x6d, 0x20, 0x3f, 0x33, 0xf5, 0x81, 0x85, 0xb4, 0x1d,
	0xf5, 0x99, 0x4d, 0xdf, 0x7d, 0x0e, 0x5b, 0x19, 0xd4, 0xce, 0xbf, 0x0f, 0x79, 0x15, 0xf5, 0x99,
	0x54, 0xb4, 0x9f, 0x60, 0x84, 0xf9, 0xe6, 0x18, 0x70, 0xff, 0xc8, 0x41, 0xf1, 0x5d, 0x47, 0x32,
	0x31, 0x60, 0xb8, 0x4e, 0xa7, 0xa9, 0x1c, 0x95, 0xfc, 0x99, 0xad, 0x61, 0xae, 0x32, 0x5f, 0x5d,
	0x3b, 0xde, 0x37, 0x35, 0xb4, 0xa7, 0x66, 0x70, 0x54, 0x3b, 0x4d, 0x25, 0x3a, 0xc6, 0x55, 0x23,
	0x7b, 0x90, 0x37, 0xa7, 0xd3, 0x8b, 0x02, 0x9b, 0xf2, 0xb2, 0x01, 0x2e, 0x02, 0xb2, 0x0b, 0xcb,
	0x09, 0x15, 0xea, 0x5a, 0x73, 0xf3, 0xc8, 0x2d, 0xe1, 0xf8, 0x22, 0x20, 0xf7, 0x01, 0x3a, 0x54,
	0xf9, 0x5d, 0x4f, 0x46, 0x9f, 0x99, 0xb3, 0x60, 0x72, 0x44, 0xa4, 0x15, 0x7d, 0x66, 0xee, 0x6b,
	0x28, 0xdd, 0x4a, 0xd1, 0x7e, 0xdc, 0x33, 0x58, 0x34, 0x19, 0x61, 0x96, 0x85, 0x63, 0x67, 0x56,
	0x96, 0x4d, 0xab, 0x73, 0xb7, 0x60, 0xb3, 0xa5, 0xa8, 0x8a, 0xa4, 0x8a, 0xfc, 0xd1, 0xa7, 0xba,
	0x97, 0x40, 0x26, 0x41, 0x3b, 0xf9, 0x09, 0x80, 0xbc, 0x41, 0xed, 0xde, 0x2b, 0x65, 0xb7, 0xd2,
	0xd8, 0x34, 0x21, 0x75, 0xff, 0x06, 0x80, 0x31, 0x45, 0x1e, 0xc2, 0x4a, 0xa7, 0xc7, 0xfd, 0x2b,
	0xaf, 0xcb, 0xa2, 0xb0, 0x6b, 0x4e, 0xd9, 0x42, 0xb3, 0x80, 0xd8, 0x2b, 0x84, 0xc8, 0x63, 0x58,
	0xeb, 0x50, 0xff, 0xaa, 0xc7, 0x43, 0xaf, 0xc7, 0xe2, 0x50, 0x99, 0x15, 0x5f, 0x68, 0xae, 0x5a,
	0xf4, 0x0d, 0x82, 0xe4, 0x00, 0x0a, 0x8a, 0x2b, 0xda, 0xf3, 0x12, 0xc6, 0x84, 0xc4, 0x32, 0x2e,
	0x34, 0x01, 0xa1, 0x86, 0x46, 0x74, 0xa8, 0x90, 0xc5, 0x4c, 0x46, 0xd2, 0xd3, 0x6b, 0x8c, 0xb5,
	0xcc, 0x37, 0x0b, 0x16, 0xd3, 0xfb, 0x42, 0x4b, 0xfc, 0x54, 0x08, 0x16, 0x2b, 0x23, 0xb9, 0x67,
	0x24, 0x16, 0x43, 0xc9, 0x1e, 0xe4, 0xf5, 0x57, 0x1a, 0x7e, 0xd1, 0xac, 0xe3, 0xc0, 0xee, 0x2b,
	0xf2, 0x04, 0x16, 0xf5, 0xa7, 0xa6, 0xd2, 0x59, 0xc2, 0xc3, 0xb5, 0x69, 0x2a, 0x82, 0x47, 0xbd,
	0x85, 0x44, 0xd3, 0x0a, 0x48, 0x05, 0x56, 0xd4, 0xd0, 0x4b, 0x98, 0xf0, 0xf0, 0x5b, 0x9d, 0x65,
	0x9b, 0xef, 0xb0, 0xc1, 0xc4, 0xa9, 0x46, 0x48, 0x15, 0x36, 0xe8, 0x80, 0x09, 0x1a, 0x32, 0x4f,
	0x0d, 0xbd, 0xce, 0xb5, 0x62, 0xd2, 0xc9, 0xa3, 0x6a, 0xcd, 0xe2, 0xed, 0xe1, 0xa9, 0x46, 0xc9,
	0x09, 0x38, 0x23, 0x25, 0x17, 0x01, 0x13, 0x72, 0x62, 0x5e, 0x40, 0xc7, 0x8e, 0xe5, 0xdf, 0x21,
	0x7d, 0x13, 0xe2, 0x29, 0x6c, 0x2a, 0x41, 0x03, 0x66, 0x0c, 0x92, 0xf9, 0x3c, 0x0e, 0x9c, 0x02,
	0x3a, 0xd6, 0x0d, 0xd1, 0x60, 0xa2, 0x85, 0xb0, 0xd6, 0x4e, 0x4c, 0x6e, 0xb5, 0x2b, 0x46, 0xcb,
	0x47, 0xd3, 0x5a, 0xed, 0x23, 0x58, 0x35, 0x6b, 0x61, 0x2f, 0x24, 0x67, 0x15, 0x75, 0x2b, 0x08,
	0x5e, 0x1a, 0x0c, 0x83, 0xa3, 0x88, 0xf6, 0x59, 0x1c, 0x98, 0xcc, 0x9d, 0x0d, 0x1b, 0x5c, 0x13,
	0x2f, 0x34, 0x8e, 0x19, 0x93, 0x6f, 0x81, 0x18, 0xad, 0xaf, 0x2f, 0xb2, 0x9e, 0x15, 0x6f, 0xa2,
	0x78, 0x03, 0x99, 0x33, 0x24, 0xa6, 0xd5, 0x82, 0x51, 0x65, 0x8b, 0xe2, 0x90, 0x49, 0x35, 0x12,
	0x46, 0xfd, 0x10, 0x4c, 0x5e, 0xb6, 0x76, 0xce, 0x96, 0xd9, 0x82, 0x88, 0x99, 0x7a, 0x8d, 0x25,
	0xa6, 0x28, 0xce, 0xf6, 0x84, 0xa4, 0x8d, 0x10, 0xa9, 0xc3, 0x16, 0xfa, 0x3d, 0x99, 0x76, 0xa4,
	0x2f, 0xa2, 0x44, 0x37, 0x32, 0xe9, 0xec, 0x54, 0x72, 0xd5, 0xd5, 0x26, 0x41, 0xaa, 0x35, 0xc9,
	0x68, 0x03, 0xce, 0x36, 0x65, 0x28, 0x1a, 0x03, 0x52, 0x59, 0xc3, 0x11, 0x6c, 0xfb, 0x34, 0x0e,
	0x7a, 0xd3, 0x8e, 0x12, 0x3a, 0xb6, 0x0c, 0x97, 0xb5, 0xfc, 0x00, 0x65, 0xdb, 0x74, 0x02, 0x96,
	0xa8, 0xee, 0x94, 0xd1, 0x41, 0xa3, 0x63, 0x14, 0x2f, 0xb5, 0x20, 0xeb, 0x3e, 0x81, 0x52, 0xc2,
	0x65, 0x84, 0x83, 0x29, 0xeb, 0x2e, 0x5a, 0x8b, 0x37, 0x74, 0xd6, 0xf8, 0x1c, 0x76, 0xa8, 0xef,
	0xf3, 0x34, 0x56, 0x53, 0xb6, 0x32, 0xda, 0xb6, 0x2d, 0x99, 0x35, 0x7d, 0x0f, 0xbb, 0xa3, 0x5c,
	0xa9, 0xa2, 0x53, 0xc6, 0x3d, 0x34, 0x96, 0x6c, 0xaa, 0x54, 0xd1, 0xac, 0x57, 0x1f, 0x95, 0x24,
	0xf1, 0x06, 0x4c, 0xc8, 0x88, 0xc7, 0xe6, 0x5a, 0xd8, 0xc7, 0xb3, 0xb9, 0x46, 0x93, 0xe4, 0x83,
	0x81, 0xf5, 0xf5, 0xa0, 0xbb, 0xc4, 0x84, 0xd2, 0xb9, 0x8f, 0x22, 0x18, 0x8b, 0xf4, 0xd6, 0xf5,
	0xf5, 0x71, 0xbd, 0x91, 0x3c, 0x40, 0xc9, 0x0a, 0x82, 0x23, 0x91, 0x6e, 0x49, 0xd8, 0xb5, 0x82,
	0x54, 0x50, 0x9d, 0x82, 0x73, 0x60, 0x5b, 0x92, 0x46, 0x5f, 0x5a, 0x90, 0x14, 0x61, 0x31, 0x4d,
	0xb0, 0x51, 0x54, 0xcc, 0x1d, 0x65, 0x46, 0xba, 0xdd, 0x9b, 0x18, 0x51, 0xe0, 0x3c, 0x34, 0xed,
	0x1e, 0xc7, 0x17, 0x01, 0x79, 0x0d, 0x6e, 0x66, 0xc5, 0xd2, 0x24, 0xa0, 0x8a, 0x4d, 0x97, 0xdf,
	0xc5, 0x72, 0x1c, 0x4c, 0xac, 0xdc, 0x7b, 0xa3, 0xcb, 0x94, 0xc5, 0x75, 0xa0, 0xf8, 0x86, 0x4a,
	0x75, 0x3a, 0x6e, 0xa6, 0xa3, 0xa6, 0x7e, 0x04, 0xa5, 0x5b, 0x8c, 0xed, 0xec, 0x45, 0x58, 0xcc,
	0xf4, 0x62, 0x3b, 0x3a, 0xfe, 0x73, 0x01, 0x0a, 0x67, 0x5c, 0xb0, 0x16, 0x13, 0x83, 0xc8, 0x67,
	0xa4, 0x03, 0x9b, 0xb7, 0x2e, 0x6e, 0xf2, 0xf8, 0x3f, 0xbd, 0x26, 0xca, 0x5f, 0x7d, 0x49, 0x66,
	0x73, 0xe9, 0xc2, 0xd6, 0x1d, 0xef, 0x25, 0xf2, 0x75, 0xc6, 0x3e, 0xfb, 0xf1, 0x56, 0xae, 0x7e,
	0x59, 0x68, 0x23, 0x5d, 0x66, 0x6e, 0xa5, 0x07, 0xb3, 0x6e, 0x32, 0x3b, 0xef, 0xc1, 0x4c, 0xde,
	0x4e, 0xf7, 0x2b, 0xac, 0x4f, 0xd5, 0x97, 0x3c, 0xca, 0x78, 0xee, 0x5e, 0x97, 0xf2, 0xff, 0xff,
	0x5d, 0x64, 0x67, 0x6f, 0x40, 0x61, 0xe2, 0x35, 0x43, 0xb2, 0xd9, 0xdc, 0x7e, 0xfd, 0x94, 0x2b,
	0xb3, 0x05, 0x76, 0xc6, 0xdf, 0x60, 0x7d, 0xea, 0x19, 0x31, 0x95, 0xef, 0xdd, 0xef, 0xa0, 0xa9,
	0x7c, 0x67, 0xbc, 0x44, 0xaa, 0xb9, 0x67, 0xb9, 0xd3, 0xc3, 0x5f, 0xbe, 0xf1, 0x79, 0xc0, 0x50,
	0x8f, 0xef, 0x6e, 0x9f, 0xf7, 0x6a, 0x11, 0xaf, 0xcb, 0xe0, 0xea, 0x30, 0xe4, 0x3d, 0x1a, 0x87,
	0xf5, 0x89, 0x3f, 0x3e, 0x9d, 0x45, 0xd4, 0x3c, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x56, 0x4b,
	0xc9, 0xf8, 0x0e, 0x0d, 0x00, 0x00,
}
